<?php

// Per-request accounting of the notifications a game generates, and
// enforcement of BGA's limit on their total size.
//
// BGA does not send notifications as game code produces them: they are
// bundled up, and the bundle goes out once the request has finished
// (LocalArena does the same; see `Table::doAction()` and
// `Table::sendCommittedNotifs()`).  A bundle therefore covers the
// action AND every state transition that followed it synchronously --
// and it may not exceed 128 KiB.  A request that generates more than
// that FAILS, with
//
//   generated notifications are larger than 128k (140501)
//
// which the player sees as "Unexpected error: Error: generated
// notifications are larger than 128k (140501)".  The move is lost.
//
// This is an easy limit to blow through by accident and a nasty one to
// meet for the first time in production, because it is not any single
// notification that is too big: it is everything one action produced,
// added together.  A cascade of "game"-type states that each send a
// few kilobytes can fail even though every individual notify call
// looks perfectly reasonable.  LocalArena therefore keeps the same
// books BGA does, so that a game's tests fail here rather than on the
// site.
//
// What we count is the serialized notification -- the same JSON that
// goes into the `gamelog` row -- counted once per
// `notifyAllPlayers()` / `notifyPlayer()` call rather than once per
// recipient.  That is our model of BGA's "generated notifications";
// BGA's exact byte-for-byte accounting is not documented, so a game
// sitting a few percent under the limit here might still be over it
// there.  Treat the limit as the cliff edge it is and stay well clear
// of it, rather than tuning a game to just barely fit.

require_once APP_GAMEMODULE_PATH . 'module/table/feException.php';
require_once APP_GAMEMODULE_PATH . 'module/table/BgaVisibleSystemException.php';

// Thrown at the request boundary when the notifications generated by
// one request come to more than the limit.
//
// It extends `BgaVisibleSystemException` because BGA reports this to
// the player as an unexpected (system) error rather than as anything
// the player did wrong; game code that catches BGA's system-exception
// type will catch this too.
class LocalArenaNotifSizeLimitException extends \BgaVisibleSystemException
{
  private int $total_bytes_;
  private int $limit_bytes_;
  private array $breakdown_;

  // $breakdown is the notification-type breakdown of the offending
  // bundle, in the shape `LocalArenaNotifBudget::breakdown()` returns.
  public function __construct(int $total_bytes, int $limit_bytes, array $breakdown = [])
  {
    parent::__construct(self::formatMessage($total_bytes, $limit_bytes));

    $this->total_bytes_ = $total_bytes;
    $this->limit_bytes_ = $limit_bytes;
    $this->breakdown_ = $breakdown;
  }

  // BGA's own wording for this failure, e.g.
  //
  //   generated notifications are larger than 128k (140501)
  public static function formatMessage(int $total_bytes, int $limit_bytes): string
  {
    return 'generated notifications are larger than ' . self::formatLimit($limit_bytes) . ' (' . $total_bytes . ')';
  }

  // Renders the limit the way BGA renders its own: "128k".  A limit
  // that is not a whole number of kibibytes is spelled out in bytes
  // instead; only LocalArena can have one of those, and only because
  // a test asked for it.
  private static function formatLimit(int $limit_bytes): string
  {
    if ($limit_bytes > 0 && $limit_bytes % 1024 === 0) {
      return intdiv($limit_bytes, 1024) . 'k';
    }
    return $limit_bytes . ' bytes';
  }

  // The size of the bundle the request generated, in bytes.
  public function totalBytes(): int
  {
    return $this->total_bytes_;
  }

  // The limit that was exceeded, in bytes.
  public function limitBytes(): int
  {
    return $this->limit_bytes_;
  }

  // Which notification types made up the bundle; see
  // `LocalArenaNotifBudget::breakdown()`.
  public function breakdown(): array
  {
    return $this->breakdown_;
  }
}

// The running total of notification bytes generated by the request in
// flight.  A `Table` owns one of these: it is reset when a request
// begins, added to by every notify call, and checked at the request
// boundary.
class LocalArenaNotifBudget
{
  // BGA's limit on the total size of the notifications generated while
  // handling one request.
  const BGA_LIMIT_BYTES = 128 * 1024;

  // A limit of zero means "not enforced": no bundle is ever too big.
  // Tests that deliberately generate enormous notifications -- and
  // games with a known overrun that is not what they are testing right
  // now -- can opt out this way.
  const NO_LIMIT = 0;

  private int $limit_bytes_;

  private int $total_bytes_ = 0;
  private int $count_ = 0;

  // notification type => ['bytes' => int, 'count' => int]
  private array $by_type_ = [];

  public function __construct(int $limit_bytes = self::BGA_LIMIT_BYTES)
  {
    $this->setLimit($limit_bytes);
  }

  // The limit currently in force, in bytes (`NO_LIMIT` if none).
  public function limit(): int
  {
    return $this->limit_bytes_;
  }

  public function setLimit(int $limit_bytes): void
  {
    if ($limit_bytes < 0) {
      throw new \feException('A notification size limit cannot be negative: ' . $limit_bytes);
    }
    $this->limit_bytes_ = $limit_bytes;
  }

  // True unless the limit has been turned off (see `NO_LIMIT`).
  public function enforced(): bool
  {
    return $this->limit_bytes_ !== self::NO_LIMIT;
  }

  // Forgets everything recorded so far, leaving the limit alone.
  // Called when a request begins: each request gets its own bundle,
  // and so its own budget.
  public function reset(): void
  {
    $this->total_bytes_ = 0;
    $this->count_ = 0;
    $this->by_type_ = [];
  }

  // Records one generated notification of $bytes bytes.
  public function record(string $notification_type, int $bytes): void
  {
    $this->total_bytes_ += $bytes;
    $this->count_ += 1;

    if (!array_key_exists($notification_type, $this->by_type_)) {
      $this->by_type_[$notification_type] = ['bytes' => 0, 'count' => 0];
    }
    $this->by_type_[$notification_type]['bytes'] += $bytes;
    $this->by_type_[$notification_type]['count'] += 1;
  }

  // The size of the bundle so far, in bytes.
  public function total(): int
  {
    return $this->total_bytes_;
  }

  // How many notifications have gone into it.
  public function count(): int
  {
    return $this->count_;
  }

  // The bundle broken down by notification type, as
  // `type => ['bytes' => int, 'count' => int]`, biggest contributor
  // first.
  public function breakdown(): array
  {
    $by_type = $this->by_type_;
    uasort($by_type, fn($a, $b) => $b['bytes'] <=> $a['bytes']);
    return $by_type;
  }

  public function exceeded(): bool
  {
    return $this->enforced() && $this->total_bytes_ > $this->limit_bytes_;
  }

  // Throws `LocalArenaNotifSizeLimitException` iff the bundle is over
  // the limit.  Called at the request boundary, before the action's
  // transaction commits.
  public function requireWithinLimit(): void
  {
    if ($this->exceeded()) {
      throw new LocalArenaNotifSizeLimitException($this->total_bytes_, $this->limit_bytes_, $this->breakdown());
    }
  }

  // A human-readable summary of what the request generated, most
  // expensive notification type first.  BGA reports only a total,
  // which leaves you to guess where it came from; LocalArena logs this
  // alongside the failure.
  public function describe(): string
  {
    $lines = [
      'Notifications generated during this request: ' .
      $this->total_bytes_ .
      ' bytes in ' .
      $this->count_ .
      ' notification(s); limit is ' .
      ($this->enforced() ? $this->limit_bytes_ . ' bytes' : 'not enforced') .
      '.',
    ];
    foreach ($this->breakdown() as $type => $entry) {
      $lines[] = '  ' . $type . ': ' . $entry['bytes'] . ' bytes in ' . $entry['count'] . ' notification(s)';
    }
    return implode("\n", $lines);
  }
}
