<?php

const CARD_DATA = array(
  "bros" => array(
    "acrobat" => array(
      "title" => "Acrobat",
      "image" => "acrobat",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "hacker" => array(
      "title" => "Hacker",
      "image" => "hacker",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "hawk" => array(
      "title" => "Hawk",
      "image" => "hawk",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "juicer" => array(
      "title" => "Juicer",
      "image" => "juicer",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "peterman" => array(
      "title" => "Peterman",
      "image" => "peterman",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "raven" => array(
      "title" => "Raven",
      "image" => "raven",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "rigger" => array(
      "title" => "Rigger",
      "image" => "rigger",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "rook" => array(
      "title" => "Rook",
      "image" => "rook",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "spotter" => array(
      "title" => "Spotter",
      "image" => "spotter",
      "bro" => "undefined",
      "back" => "undefined",
    ),
  ),
  "gear" => array(
    "adrenaline" => array(
      "title" => "Adrenaline",
      "image" => "adrenaline",
      "bro" => "juicer",
      "back" => "take-heat",
    ),
    "bingo" => array(
      "title" => "Bingo",
      "image" => "bingo",
      "bro" => "juicer",
      "back" => "give-action",
    ),
    "fainting" => array(
      "title" => "Fainting",
      "image" => "fainting",
      "bro" => "juicer",
      "back" => "make-commotion",
    ),
    "crybaby" => array(
      "title" => "Crybaby",
      "image" => "crybaby",
      "bro" => "juicer",
      "back" => "give-action",
    ),
    "fake-mustache" => array(
      "title" => "Fake Mustache",
      "image" => "fake-mustache",
      "bro" => "acrobat",
      "back" => "take-heat",
    ),
    "grappling-hook" => array(
      "title" => "Grappling Hook",
      "image" => "grappling-hook",
      "bro" => "acrobat",
      "back" => "give-action",
    ),
    "zipline" => array(
      "title" => "Zipline",
      "image" => "zipline",
      "bro" => "acrobat",
      "back" => "make-commotion",
    ),
    "double-flip" => array(
      "title" => "Double Flip",
      "image" => "double-flip",
      "bro" => "acrobat",
      "back" => "make-commotion",
    ),
    "bird-tricks" => array(
      "title" => "Bird Tricks",
      "image" => "bird-tricks",
      "bro" => "raven",
      "back" => "take-heat",
    ),
    "fowl-play" => array(
      "title" => "Fowl Play",
      "image" => "fowl-play",
      "bro" => "raven",
      "back" => "give-action",
    ),
    "free-bird" => array(
      "title" => "Free Bird",
      "image" => "free-bird",
      "bro" => "raven",
      "back" => "make-commotion",
    ),
    "all-in" => array(
      "title" => "All In",
      "image" => "all-in",
      "bro" => "raven",
      "back" => "take-heat",
    ),
    "clairvoyant" => array(
      "title" => "Clairvoyant",
      "image" => "clairvoyant",
      "bro" => "spotter",
      "back" => "take-heat",
    ),
    "mind-tricks" => array(
      "title" => "Mind Tricks",
      "image" => "mind-tricks",
      "bro" => "spotter",
      "back" => "give-action",
    ),
    "telekinesis" => array(
      "title" => "Telekinesis",
      "image" => "telekinesis",
      "bro" => "spotter",
      "back" => "make-commotion",
    ),
    "stacked-deck" => array(
      "title" => "Stacked Deck",
      "image" => "stacked-deck",
      "bro" => "spotter",
      "back" => "take-heat",
    ),
    "macgyver" => array(
      "title" => "MacGyver",
      "image" => "macgyver",
      "bro" => "rigger",
      "back" => "take-heat",
    ),
    "scaffolding" => array(
      "title" => "Scaffolding",
      "image" => "scaffolding",
      "bro" => "rigger",
      "back" => "give-action",
    ),
    "sledgehammer" => array(
      "title" => "Sledgehammer",
      "image" => "sledgehammer",
      "bro" => "rigger",
      "back" => "make-commotion",
    ),
    "folding-ladder" => array(
      "title" => "Folding Ladder",
      "image" => "folding-ladder",
      "bro" => "rigger",
      "back" => "give-action",
    ),
    "mirage" => array(
      "title" => "Mirage",
      "image" => "mirage",
      "bro" => "hawk",
      "back" => "take-heat",
    ),
    "sliding-door" => array(
      "title" => "Sliding Door",
      "image" => "sliding-door",
      "bro" => "hawk",
      "back" => "give-action",
    ),
    "special-offer" => array(
      "title" => "Special Offer",
      "image" => "special-offer",
      "bro" => "hawk",
      "back" => "make-commotion",
    ),
    "air-ducts" => array(
      "title" => "Air Ducts",
      "image" => "air-ducts",
      "bro" => "hawk",
      "back" => "give-action",
    ),
    "loop-footage" => array(
      "title" => "Loop Footage",
      "image" => "loop-footage",
      "bro" => "hacker",
      "back" => "take-heat",
    ),
    "out-of-order" => array(
      "title" => "Out of Order",
      "image" => "out-of-order",
      "bro" => "hacker",
      "back" => "give-action",
    ),
    "radio-interference" => array(
      "title" => "Radio Interference",
      "image" => "radio-interference",
      "bro" => "hacker",
      "back" => "make-commotion",
    ),
    "hack" => array(
      "title" => "Hack",
      "image" => "hack",
      "bro" => "hacker",
      "back" => "take-heat",
    ),
    "earpiece" => array(
      "title" => "Earpiece",
      "image" => "earpiece",
      "bro" => "rook",
      "back" => "take-heat",
    ),
    "face-masks" => array(
      "title" => "Face Masks",
      "image" => "face-masks",
      "bro" => "rook",
      "back" => "give-action",
    ),
    "impersonate" => array(
      "title" => "Impersonate",
      "image" => "impersonate",
      "bro" => "rook",
      "back" => "make-commotion",
    ),
    "body-double" => array(
      "title" => "Body Double",
      "image" => "body-double",
      "bro" => "rook",
      "back" => "give-action",
    ),
    "get-cracking" => array(
      "title" => "Get Cracking",
      "image" => "get-cracking",
      "bro" => "peterman",
      "back" => "take-heat",
    ),
    "good-intel" => array(
      "title" => "Good Intel",
      "image" => "good-intel",
      "bro" => "peterman",
      "back" => "give-action",
    ),
    "improvised-route" => array(
      "title" => "Improvised Route",
      "image" => "improvised-route",
      "bro" => "peterman",
      "back" => "make-commotion",
    ),
    "altered-id-badge" => array(
      "title" => "Altered ID Badge",
      "image" => "altered-id-badge",
      "bro" => "peterman",
      "back" => "undefined",
    ),
  ),
  "gearBack" => array(
  ),
  "deaddrops" => array(
    "0" => array(
      "title" => "Dead Drops",
      "image" => "0",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "1" => array(
      "title" => "Dead Drops",
      "image" => "1",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "2" => array(
      "title" => "Dead Drops",
      "image" => "2",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "3" => array(
      "title" => "Dead Drops",
      "image" => "3",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "4" => array(
      "title" => "Dead Drops",
      "image" => "4",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "5" => array(
      "title" => "Dead Drops",
      "image" => "5",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "6" => array(
      "title" => "Dead Drops",
      "image" => "6",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "7" => array(
      "title" => "Dead Drops",
      "image" => "7",
      "bro" => "undefined",
      "back" => "undefined",
    ),
  ),
  "lounge" => array(
    "directions" => array(
      "title" => "Directions",
      "image" => "directions",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "happy-hour" => array(
      "title" => "Happy Hour",
      "image" => "happy-hour",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "chatterbox" => array(
      "title" => "Chatterbox",
      "image" => "chatterbox",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "espresso-bar" => array(
      "title" => "Espresso Bar",
      "image" => "espresso-bar",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "share-a-drink" => array(
      "title" => "Share a Drink",
      "image" => "share-a-drink",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "tipsy" => array(
      "title" => "Tipsy",
      "image" => "tipsy",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "thirsty" => array(
      "title" => "Thirsty",
      "image" => "thirsty",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "dubious-meeting" => array(
      "title" => "Dubious Meeting",
      "image" => "dubious-meeting",
      "bro" => "undefined",
      "back" => "undefined",
    ),
  ),
  "pool" => array(
    "splash-zone" => array(
      "title" => "Splash Zone",
      "image" => "splash-zone",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "cannonball" => array(
      "title" => "Cannonball",
      "image" => "cannonball",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "pool-prank" => array(
      "title" => "Pool Prank",
      "image" => "pool-prank",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "trade-shifts" => array(
      "title" => "Trade Shifts",
      "image" => "trade-shifts",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "identity-theft" => array(
      "title" => "Identity Theft",
      "image" => "identity-theft",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "go-for-a-swim" => array(
      "title" => "Go For A Swim",
      "image" => "go-for-a-swim",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "lifeguard-tip" => array(
      "title" => "Lifeguard Tip",
      "image" => "lifeguard-tip",
      "bro" => "undefined",
      "back" => "undefined",
    ),
    "no-running" => array(
      "title" => "No Running!",
      "image" => "no-running",
      "bro" => "undefined",
      "back" => "undefined",
    ),
  ),
  "finale" => array(
  ),
);
